### 보스턴의 집값에 영향을 미치는 요소들을 입력값으로 두고 나오는 집값들이 출력값이다.
### 입력 요소엔 범죄율, 접근성, 흑인수, 저속등층, 찰스강이 보이는가 등 다양한 요소들이 있다. 

### 일반적으로 우리가 공부하는 Y=aX+b에서 Y는 대게 레그레션한(연속적인)값이다. 허나 우리가 원하는 현실의 값들은 주로  yes or no/ red or blue 같이 categorical한 값이기 때문에 우리는  해당 식을 sigmoid 등의 식을 이용해 not linear 하게 만들어준다.

In [1]:
# description
# https://www.kaggle.com/c/boston-housing

# TensorFlow and tf.keras
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

### boston_housing.npz 이 파일이 부재해서 진행이 안되는 것 같습니다.

In [2]:
(x_train, y_train), (x_test, y_test) = 
tensorflow.keras.datasets.boston_housing.load_data(path='boston_housing.npz')

SyntaxError: invalid syntax (<ipython-input-2-769ce6932225>, line 1)


###  Sequential 한 모델이다. 
### model.add(Dense(1, input_shape=[13])) - [13]:입력이 13개 1: 출력이 1개인 상태
### Dense : fully connected (오밀조밀하게 서로서로 다 연결 돼있는것)


In [4]:
model = Sequential()
model.add(Dense(1, input_shape=[13]))
model.compile(optimizer='rmsprop', loss='mse')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 14        
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


model.fit() - 만든 모델을 트레이닝하는 것
epochs=1000 1000번 돌린다.

In [5]:
model.fit(x_train, y_train, epochs=1000)

NameError: name 'x_train' is not defined

### 만든 모델을 평가한다.

In [6]:
model.evaluate(x_test, y_test)

NameError: name 'x_test' is not defined

In [7]:
print(model.input_shape)
print(model.output_shape)

(None, 13)
(None, 1)


In [8]:
# INPUT::
# 1. crim: per capita crime rate by town.
# 2. zn: proportion of residential land zoned for lots over 25,000 sq.ft.
# 3. indus: proportion of non-retail business acres per town.
# 4. chas: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise).
# 5. nox: nitrogen oxides concentration (parts per 10 million).
# 6. rm: average number of rooms per dwelling.
# 7. age: proportion of owner-occupied units built prior to 1940.
# 8. dis: weighted mean of distances to five Boston employment centres.
# 9. rad: index of accessibility to radial highways.
# 10. tax: full-value property-tax rate per $10,000.
# 11. ptratio: pupil-teacher ratio by town.
# 12. black: 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town.
# 13. lstat: lower status of the population (percent).

# TARGET::
# medv: median value of owner-occupied homes in $1000s.

model.predict(np.array([0, 1, 50, 1, 0, 5, .5, 10, 1000, 100, 10, 100, 1]).reshape(1,13))

array([[576.7395]], dtype=float32)

### 범죄율과 주거지 비율, 찰스강이 안보이게 되자 집값이 떨어졌음을 확인할 수 있습니다.

In [9]:
model.predict(np.array([3, 3, 20, 0, 1, 1, .2, 10, 1000, 100, 10, 100, 1]).reshape(1,13))

array([[559.05475]], dtype=float32)

indus,rm,dis,rad 등의 값을 긍정적으로 변화시키자 집 값이 올랐음을 확인 할 수 있습니다.

In [10]:
model.predict(np.array([0, 1, 100, 1, 0, 15, .5, 30, 1000, 100, 10, 100, 1]).reshape(1,13))

array([[610.7368]], dtype=float32)