### int란 정수를 의미한다.변수 a는 1이기 때문에 정수에 속한다. type()은 변수의 class를 보여준다.때문에 print()를 했을 때 나오는 결과값은 <class 'int'>이다. 

In [34]:
a = 1; print(type(a))

<class 'int'>


### 변수a=1은 정수 int지만 여기선 a=float(a)를 해줌으로써 변수 a를 float으로 설정해준다. 따라서 a의 타입을 프린트하면 int가 아닌 float이나온다.

In [35]:
a = 1; a = float(a); print(type(a))

<class 'float'>


### a=1.2는 float이지만 a= int(a)를 해줌으로써 a를 int로 설정해준다. 따라서 a의 타입을 프린트하면 float이 아닌 int가 나온다.

In [36]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


### 123은 int이지만 ''를 씌워줌으로써 str이 된다. 때문에 a의 타입을 프린트하면 str이라 나온다. a[1]은 '123'의 첫번째를 뜻하는게 아닌 두번째다. 0부터 새기 때문이다. 따라서 1이 아닌 2가 프린트 된다.

In [38]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


### a='123'은 str이지만 a=list(a)에 의해 a는 리스트로 설정된다. 때문에 a의 타입은 list로 프린트된다. 또한 a를 프린트하면 list로 설정됐기 때문에 '123'이 아닌 리스트의 형태인 ['1','2','3']로 프린트 된다. a[2]는 0부터 새면 세번째이기 때문에 3이 출력된다.

In [40]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


### a = [1,'2', [3, '4']] 처럼 list안에 list를 넣는 것도 가능하다. a=[]형태는 모두 list이다. 때문에 a의 타입을 프린트하면 리스트가 된다. a[2]는 리스트의 변수 중 세번째 변수인 [3,'4']이가 출력된다.

In [43]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


### 위와 거의 유사하나 [ ]가 아닌 ( )가 사용됐다. ( )는 tuple이라고 한다. 리스트와 큰 차이는 없다.

In [42]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


#### "a":"apple"은 "a"를 "apple"로 설정해준다. 따라서 "a"를 프린트 해주면 "apple"이나온다. 여기서 a와 "a"는 다른 것임을 구분해줘야 한다.
#### a =	{"a": "apple", "b": "orange", "c": 2014}의 타입은 dict이다.

In [45]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [1]:
a=1; b=2

In [2]:
print(a)

print(b)

1
2


In [3]:
b

a

1

In [4]:
type(a)

int

In [5]:
a=1.0

type(a)

float

In [6]:
a=1.1

int(a)

1

In [7]:
float(int(a))

1.0

In [8]:
a=1;a=float(a); print(type(a))

<class 'float'>


In [9]:
a=1.2; a=int(a); print(type(a))

<class 'int'>


In [10]:
a='123'

In [11]:
a

'123'

In [12]:
type(a)

str

In [13]:
a='abc'

In [14]:
a

'abc'

In [15]:
a[-1]

'c'

In [16]:
a=[1,2,3]

In [17]:
a

[1, 2, 3]

In [18]:
type(a)

list

In [19]:
a=[1,2,'ab',[4,5]]

In [20]:
a[0]

1

In [21]:
a[-1][0]

4

In [22]:
a='123'; a=list(a)

In [23]:
a

['1', '2', '3']

In [30]:
a={"a" :"apple", "b" : "orange", "c" : '2014'}
print(a)

{'a': 'apple', 'b': 'orange', 'c': '2014'}


In [31]:
type(a)

dict

In [32]:
print(a)

{'a': 'apple', 'b': 'orange', 'c': '2014'}


In [33]:
print(type(a))

<class 'dict'>


### a는 리스트다. 파이썬에는 행렬 함수가 포함되어 있지 않기 때문에 따로 함수를 import 해오지 않으면 [(1,2,3), (3,8,0)]의 결과값은 평범한 리스트로 출력된다.

In [50]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

### import는 파이썬에는 포함되어 있지 않은 외부의 함수를 가져오는 기능이다. import numpy는 anaconda와 함께 받은 하드 디스크 상의 numpy에 있는 함수 기능들을 메모리에 띄우는 것이다. as np는 매번 numpy라 쓰는 번거로움을 피하기 위해 numpy를 np로 설정하는 것이다. numpy에 포함되어 있는 array의 기능은 행렬과 유사한 형태로 변수들을 나열해주는 것이다. [(1,2,3),(8,3,0)]에서 행의 구분 기준은","이다.  따라서 아래와 같은 결과 값이 나오는 것이다. 

In [51]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


### array는 행렬과 유사하지만 다르다. 때문에 행렬이라면 2x3는 3XN과만 곱해지는데 아래와 같이 결과값이 제대로 출력됐다.

In [52]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


### 위에서 numpy를 이미 import 해왔고 또 np 로 설정해뒀기 때문에 np.matrix라고 쓰는 것만으로 행렬 함수 기능을 사용할 수 있다. 형태는 array와 비슷하다.

In [55]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


### 형태는 array와 비슷하지만 array 와 달리 행렬이기 때문에 2x3은 3xn 과만 곱할 수 있다.

In [57]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

###.T는 2x3 행렬을 3x2의 형태로 바꿔줘 곱셈을 가능하게 해준다.

In [59]:
c*c.T

matrix([[14, 19],
        [19, 73]])

In [62]:
a=[(1,2,3),(3,8,0),(2,0,3)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0), (2, 0, 3)]

In [63]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]
 [2 0 3]]
<class 'numpy.ndarray'>


In [64]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]
 [ 4  0  9]]


In [67]:
a=[(1,2),(8,0)]
print(type(a))
a

<class 'list'>


[(1, 2), (8, 0)]

In [69]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2]
 [8 0]]
<class 'numpy.ndarray'>


In [71]:
print(b*b)

[[ 1  4]
 [64  0]]


In [72]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2]
 [8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [73]:
c*c

matrix([[17,  2],
        [ 8, 16]])

In [74]:
b*c

matrix([[17,  2],
        [ 8, 16]])